# Generated by Django 5.2.16 on 2026-07-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='identity_method',
            field=models.CharField(blank=True, choices=[('online', 'Pemeriksaan online'), ('face_to_face', 'Pemeriksaan tatap muka')], max_length=20, verbose_name='Metode pemeriksaan identitas'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='identity_notes',
            field=models.TextField(blank=True, verbose_name='Catatan pemeriksaan'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='identity_status',
            field=models.CharField(choices=[('pending', 'Menunggu validasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status validasi identitas'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_married',
            field=models.BooleanField(default=False, verbose_name='Pasangan suami istri'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='marriage_certificate',
            field=models.FileField(blank=True, upload_to='identity_documents/marriage/', verbose_name='Bukti surat nikah'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='NIK'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu verifikasi'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
