# Generated by Django 5.2.16 on 2026-07-20 06:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama fasilitas')),
                ('icon', models.CharField(blank=True, default='✦', max_length=20, verbose_name='Ikon/emoji')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RoseHaven Hotel', max_length=150, verbose_name='Nama hotel')),
                ('tagline', models.CharField(default='A timeless stay, wrapped in comfort.', max_length=200, verbose_name='Tagline')),
                ('description', models.TextField(default='RoseHaven adalah hotel bintang 4 dengan pelayanan hangat, kamar elegan, dan fasilitas lengkap.', verbose_name='Tentang hotel')),
                ('address', models.TextField(default='Jl. Mawar Indah No. 8, Indonesia', verbose_name='Alamat')),
                ('phone', models.CharField(default='+62 812-3456-7890', max_length=30, verbose_name='No. telepon')),
                ('email', models.EmailField(default='hello@rosehaven.test', max_length=254, verbose_name='Email')),
                ('bank_name', models.CharField(default='Bank RoseHaven', max_length=80, verbose_name='Nama bank')),
                ('bank_account', models.CharField(default='1234567890', max_length=80, verbose_name='Nomor rekening')),
                ('bank_holder', models.CharField(default='RoseHaven Hotel', max_length=100, verbose_name='Atas nama')),
            ],
            options={
                'verbose_name': 'Pengaturan hotel',
                'verbose_name_plural': 'Pengaturan hotel',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama tipe')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga dasar per malam')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='Kapasitas')),
                ('bed_type', models.CharField(default='Queen Bed', max_length=100, verbose_name='Jenis tempat tidur')),
                ('size_m2', models.PositiveSmallIntegerField(default=24, verbose_name='Luas kamar (m²)')),
            ],
            options={
                'verbose_name': 'Tipe kamar',
                'verbose_name_plural': 'Tipe kamar',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Kode reservasi')),
                ('check_in', models.DateField(verbose_name='Tanggal check in')),
                ('check_out', models.DateField(verbose_name='Tanggal check out')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Jumlah tamu')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('WAITING_PAYMENT', 'Menunggu Pembayaran'), ('PAID', 'Sudah Dibayar'), ('CONFIRMED', 'Dikonfirmasi'), ('CHECKED_IN', 'Check In'), ('CHECKED_OUT', 'Check Out'), ('COMPLETED', 'Selesai'), ('CANCELED', 'Dibatalkan')], default='WAITING_PAYMENT', max_length=30, verbose_name='Status')),
                ('source', models.CharField(choices=[('ONLINE', 'Online'), ('WALK_IN', 'Datang Langsung')], default='ONLINE', max_length=20, verbose_name='Sumber reservasi')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Reservasi',
                'verbose_name_plural': 'Reservasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jumlah pembayaran')),
                ('proof', models.ImageField(blank=True, upload_to='payment_proofs/', verbose_name='Bukti transfer')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20, verbose_name='Status pembayaran')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal pembayaran')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Catatan verifikasi')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='administrator.reservation', verbose_name='Reservasi')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Nomor kamar')),
                ('name', models.CharField(max_length=120, verbose_name='Nama kamar')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga khusus')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Tersedia'), ('OCCUPIED', 'Terisi'), ('MAINTENANCE', 'Perawatan')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, upload_to='rooms/', verbose_name='Foto kamar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='rooms', to='administrator.facility', verbose_name='Fasilitas')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='administrator.roomtype', verbose_name='Tipe')),
            ],
            options={
                'verbose_name': 'Kamar',
                'verbose_name_plural': 'Kamar',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='administrator.room', verbose_name='Kamar'),
        ),
    ]
