# Generated by Django 5.2.16 on 2026-07-25 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_add_database_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'verified_at'], name='pay_status_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_in'], name='res_status_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_out'], name='res_status_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer', 'created_at'], name='res_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'is_active'], name='room_status_active_idx'),
        ),
    ]
