# Generated by Django 6.0.6 on 2026-07-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_payment_pay_status_verified_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per malam')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_rooms', to='administrator.reservation', verbose_name='Reservasi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='administrator.room', verbose_name='Kamar')),
            ],
            options={
                'verbose_name': 'Kamar reservasi',
                'verbose_name_plural': 'Kamar reservasi',
                'constraints': [models.UniqueConstraint(fields=('reservation', 'room'), name='unique_room_in_reservation')],
            },
        ),
    ]
