# Generated by Django 5.2.15 on 2026-07-28 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_payment_pay_status_verified_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='administrator.room', verbose_name='Kamar utama'),
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per malam')),
                ('key_status', models.CharField(choices=[('NOT_GIVEN', 'Belum diberikan'), ('GIVEN', 'Sudah diberikan'), ('RETURNED', 'Sudah dikembalikan'), ('PROBLEM', 'Hilang atau bermasalah')], default='NOT_GIVEN', max_length=20, verbose_name='Status kunci')),
                ('key_given_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu kunci diberikan')),
                ('key_returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu kunci dikembalikan')),
                ('key_notes', models.CharField(blank=True, max_length=255, verbose_name='Catatan/kondisi kunci')),
                ('key_given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys_given', to=settings.AUTH_USER_MODEL, verbose_name='Kunci diberikan oleh')),
                ('key_returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys_received', to=settings.AUTH_USER_MODEL, verbose_name='Kunci diterima oleh')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_rooms', to='administrator.reservation', verbose_name='Reservasi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='administrator.room', verbose_name='Kamar')),
            ],
            options={
                'verbose_name': 'Kamar reservasi',
                'verbose_name_plural': 'Kamar reservasi',
                'ordering': ['room__number'],
                'indexes': [models.Index(fields=['key_status'], name='reservation_key_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('reservation', 'room'), name='unique_room_in_reservation')],
            },
        ),
        migrations.CreateModel(
            name='StayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp_status', models.CharField(choices=[('NOT_RECEIVED', 'Belum diserahkan'), ('HELD', 'Dititipkan sebagai jaminan'), ('RETURNED', 'Sudah dikembalikan')], default='NOT_RECEIVED', max_length=20, verbose_name='Status jaminan KTP')),
                ('ktp_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu KTP diterima')),
                ('ktp_returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu KTP dikembalikan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan jaminan KTP')),
                ('ktp_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ktp_guarantees_received', to=settings.AUTH_USER_MODEL, verbose_name='KTP diterima oleh')),
                ('ktp_returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ktp_guarantees_returned', to=settings.AUTH_USER_MODEL, verbose_name='KTP dikembalikan oleh')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stay_record', to='administrator.reservation', verbose_name='Reservasi')),
            ],
            options={
                'verbose_name': 'Catatan menginap dan jaminan',
                'verbose_name_plural': 'Catatan menginap dan jaminan',
                'indexes': [models.Index(fields=['ktp_status'], name='stay_ktp_status_idx')],
            },
        ),
    ]
