# Generated by Django 6.0.6 on 2026-07-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_reservation_room_reservationroom_stayrecord'),
        ('administrator', '0004_reservationroom'),
    ]

    operations = [
    ]
