# Generated by Django 5.2.16 on 2026-07-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='No. HP')),
                ('shift', models.CharField(choices=[('MORNING', 'Pagi'), ('AFTERNOON', 'Siang'), ('NIGHT', 'Malam')], default='MORNING', max_length=20, verbose_name='Shift')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil resepsionis',
                'verbose_name_plural': 'Profil resepsionis',
            },
        ),
    ]
